spring:
  application:
    name: Scrum Board

  datasource:
    url: ${SCRUM_DB_URL}
    username: ${SCRUM_DB_USER}
    password: ${SCRUM_DB_PASS}
    driverClassName: ${SCRUM_DB_DRIVER}
    platform: ${DB_PLATFORM} # mysql or postgresql
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database-platform: ${DB_DIALECT}

app:
  frontendUrl: ${SCRUM_FRONTEND_URL}