spring:
  application:
    name: Scrum Board

  datasource:
    url: jdbc:h2:mem:scrum
    username: sa
    password:
    driverClassName: org.h2.Driver

    max-idle: 50
    suspect-timeout: 60
    time-between-eviction-runs-millis: 30000

    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

app:
  frontendUrl: http://localhost:8000